# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlp_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nlp_service.proto\x12\x03nlp\"(\n\x0f\x46\x65\x65\x64\x62\x61\x63kRequest\x12\x15\n\rfeedback_text\x18\x01 \x01(\t\"&\n\x11SentimentResponse\x12\x11\n\tsentiment\x18\x01 \x01(\t\"$\n\x10\x43\x61tegoryResponse\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t2\x95\x01\n\nNLPService\x12\x42\n\x10\x41nalyzeSentiment\x12\x14.nlp.FeedbackRequest\x1a\x16.nlp.SentimentResponse\"\x00\x12\x43\n\x12\x43\x61tegorizeFeedback\x12\x14.nlp.FeedbackRequest\x1a\x15.nlp.CategoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FEEDBACKREQUEST']._serialized_start=26
  _globals['_FEEDBACKREQUEST']._serialized_end=66
  _globals['_SENTIMENTRESPONSE']._serialized_start=68
  _globals['_SENTIMENTRESPONSE']._serialized_end=106
  _globals['_CATEGORYRESPONSE']._serialized_start=108
  _globals['_CATEGORYRESPONSE']._serialized_end=144
  _globals['_NLPSERVICE']._serialized_start=147
  _globals['_NLPSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
