# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nlp_service_pb2 as nlp__service__pb2


class NLPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSentiment = channel.unary_unary(
                '/nlp.NLPService/AnalyzeSentiment',
                request_serializer=nlp__service__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=nlp__service__pb2.SentimentResponse.FromString,
                )
        self.CategorizeFeedback = channel.unary_unary(
                '/nlp.NLPService/CategorizeFeedback',
                request_serializer=nlp__service__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=nlp__service__pb2.CategoryResponse.FromString,
                )


class NLPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeSentiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CategorizeFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentiment,
                    request_deserializer=nlp__service__pb2.FeedbackRequest.FromString,
                    response_serializer=nlp__service__pb2.SentimentResponse.SerializeToString,
            ),
            'CategorizeFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.CategorizeFeedback,
                    request_deserializer=nlp__service__pb2.FeedbackRequest.FromString,
                    response_serializer=nlp__service__pb2.CategoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlp.NLPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NLPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlp.NLPService/AnalyzeSentiment',
            nlp__service__pb2.FeedbackRequest.SerializeToString,
            nlp__service__pb2.SentimentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CategorizeFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlp.NLPService/CategorizeFeedback',
            nlp__service__pb2.FeedbackRequest.SerializeToString,
            nlp__service__pb2.CategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
